package com.baili.sharingPlatform.service.ServiceStressTestingToolsInit;

import cn.hutool.http.HttpRequest;
import com.example.test.xskytest.dal.service.DataInitializationService;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;

/**
 * @author baili
 * @date 2023年08月04日16:12
 */
@Service
public class ServiceVFourInit {

    @Resource
    private DataInitializationService dataInitializationService;

    private final String XXLJOB_INIT_SQL_FOUR = "delete from  `xxl_job`.`xxl_job_group` where app_name = 'stressTestingTools'; \n" +
            "\n" +
            "###删除baili-boot 1.2.1自动插入的执行器\n" +
            "delete from `xxl_job`.`xxl_job_group` where app_name = 'stressTestingTools'; \n" +
            "\n" +
            "##新增执行器\n" +
            "INSERT INTO `xxl_job`.`xxl_job_group` (`id`, `app_name`, `title`, `address_type`, `address_list`, `update_time`) VALUES (3, 'stressTestingTools', 'stressTestingTools', 0, '', '2021-08-11 17:01:54');\n" +
            "\n" +
            "##新增job任务\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '大盘趋势数据统计', '2021-07-16 10:29:53', '2021-07-16 10:29:53', '流苏', 'qiyong.xie@baili.com', 'CRON', '0 0 2 * * ?', 'DO_NOTHING', 'ROUND', 'trendJobHandler', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-07-16 10:29:53', '', 1, 1628618400000, 1628704800000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '计划统计数据', '2021-07-16 10:31:20', '2021-07-16 10:31:20', '流苏', 'qiyong.xie@baili.com', 'CRON', '*/30 * * * * ?', 'DO_NOTHING', 'ROUND', 'planStatisticsJobHandler', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-07-16 10:31:20', '', 1, 1628672370000, 1628672400000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '应用统计数据', '2021-07-16 10:32:26', '2021-07-16 10:32:26', '流苏', 'qiyong.xie@baili.com', 'CRON', '0/30 * * * * ?', 'DO_NOTHING', 'ROUND', 'appStatisticsJobHandler', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-07-16 10:32:26', '', 1, 1628672370000, 1628672400000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '场景的使用记录', '2021-07-16 10:33:07', '2021-07-16 10:33:07', '流苏', 'qiyong.xie@baili.com', 'CRON', '0 0 1 * * ?', 'DO_NOTHING', 'ROUND', 'calculateSceneExecJobHandler', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-07-16 10:33:07', '', 1, 1628614800000, 1628701200000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '清理场景运行的错误日志', '2021-07-16 10:34:42', '2021-07-16 10:34:42', '流苏', 'qiyong.xie@baili.com', 'CRON', '0 */1 * * * ?', 'DO_NOTHING', 'ROUND', 'cleanReportLogJobHandler', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-07-16 10:34:42', '', 1, 1628672340000, 1628672400000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '清理缓存中的数据', '2021-07-16 10:36:32', '2021-07-16 10:36:32', '流苏', 'qiyong.xie@baili.com', 'CRON', '0 */1 * * * ?', 'DO_NOTHING', 'ROUND', 'cleanReportCacheJobHandler', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-07-16 10:36:32', '', 1, 1628672340000, 1628672400000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '计划内场景的通过率', '2021-07-16 10:37:07', '2021-07-16 10:37:07', '流苏', 'qiyong.xie@baili.com', 'CRON', '0 */2 * * * ?', 'DO_NOTHING', 'ROUND', 'planScenePassRateStatisticsJobHandler', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-07-16 10:37:07', '', 1, 1628672280000, 1628672400000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '删除fastdfs文件的key历史数据', '2021-07-16 10:37:38', '2021-08-02 14:30:06', '流苏', 'qiyong.xie@baili.com', 'CRON', '0 */10 * * * ?', 'DO_NOTHING', 'ROUND', 'delHistoryFileJobHandler', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-07-16 10:37:38', '', 1, 1628671800000, 1628672400000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '报告状态更新', '2021-07-16 10:39:04', '2021-08-02 14:30:04', '流苏', 'qiyong.xie@baili.com', 'CRON', '0 */2 * * * ?', 'DO_NOTHING', 'ROUND', 'reportStatusJobHandler', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-07-16 10:39:04', '', 1, 1628672280000, 1628672400000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '释放早期的调试历史记录(剔除最近的一条历史记录)', '2021-07-16 10:39:51', '2021-08-02 14:30:01', '流苏', 'qiyong.xie@baili.com', 'CRON', '0 */5 * * * ?', 'DO_NOTHING', 'ROUND', 'releaseSceneDebugHistoryJobDataJobHandler', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-07-16 10:39:51', '', 1, 1628672100000, 1628672400000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '释放压力机占用资源', '2021-07-16 10:40:23', '2021-08-02 14:29:58', '流苏', 'qiyong.xie@baili.com', 'CRON', '0/5 * * * * ?', 'DO_NOTHING', 'ROUND', 'releaseSceneExecRecMachineObtainResourceJobHandler', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-07-16 10:40:23', '', 1, 1628672375000, 1628672380000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '释放场景执行记录', '2021-07-16 10:40:52', '2021-08-02 14:29:47', '流苏', 'qiyong.xie@baili.com', 'CRON', '0/10 * * * * ?', 'DO_NOTHING', 'ROUND', 'sceneReleaseSceneExecResourceJobHandler', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-07-16 10:40:52', '', 1, 1628672370000, 1628672380000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '运行时段超时异常处理机制', '2021-07-16 10:41:24', '2021-08-02 14:29:53', '流苏', 'qiyong.xie@baili.com', 'CRON', '0/5 * * * * ?', 'DO_NOTHING', 'ROUND', 'sceneTaskRunningStateTimeOutJobHandler', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-07-16 10:41:24', '', 1, 1628672375000, 1628672380000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '场景任务-超时异常处理机制', '2021-07-16 10:42:06', '2021-08-02 14:29:47', '流苏', 'qiyong.xie@baili.com', 'CRON', '0/5 * * * * ?', 'DO_NOTHING', 'ROUND', 'sceneTaskTimeOutJobHandler', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-07-16 10:42:06', '', 1, 1628672375000, 1628672380000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '从xcenter同步压力机数据', '2021-07-22 18:24:52', '2021-08-02 14:29:41', '维西', '', 'CRON', '0 0/2 * * * ?', 'DO_NOTHING', 'ROUND', 'syncStressMachineFormXCenter', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-07-22 18:24:52', '', 1, 1628672280000, 1628672400000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, '初始化租户的系统参数', '2021-08-16 16:10:13', '2021-08-16 16:15:48', '维西', '', 'CRON', '0 0/5 * * * ?', 'DO_NOTHING', 'ROUND', 'sysParamInitJobHandler', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-08-16 16:10:13', '', 1, 1629103200000, 1629103500000);\n" +
            "INSERT INTO `xxl_job`.`xxl_job_info` (`job_group`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`, `trigger_status`, `trigger_last_time`, `trigger_next_time`) VALUES (3, 'shell执行超时处理', '2021-10-16 20:22:09', '2021-10-16 20:24:48', '维西', '', 'CRON', '0/10 * * * * ?', 'DO_NOTHING', 'FIRST', 'checkTimeoutScriptBatch', '', 'SERIAL_EXECUTION', 0, 2, 'BEAN', '', 'GLUE代码初始化', '2021-10-16 20:22:09', '', 1, 1634387100000, 1634387110000);\n";

    public Boolean initStressTestingToolsXxljobSql (String mysqlAddress){
        String mysqlUrl = "jdbc:mysql://" + mysqlAddress +
                ":3306/?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true" +
                "&allowPublicKeyRetrieval=true&allowMultiQueries=true";
        try{
            dataInitializationService.runSqlCmd(mysqlUrl, "root", "Perfma888.", XXLJOB_INIT_SQL_FOUR);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }

    }

    public Boolean initStressTestingToolsRequest(String stressTestingToolsAddress,Boolean isLowVersion){
        try{
            String urlLowVersion = stressTestingToolsAddress+":17006/api/stressTestingTools/test/init/system";
            String urlHighVersion = stressTestingToolsAddress+"17006/api/stressTestingTools/test/init/system/test/-1";
            if(isLowVersion){
                HttpRequest.get(urlLowVersion);
            }else{
                HttpRequest.get(urlHighVersion);
            }
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }
    }
}
